# =========================================================
# NOMBRE DE LA APLICACION
# =========================================================

# Define el nombre de la aplicacion dentro del ecosistema Spring.
#
# Este nombre puede ser utilizado en:
#
# - Logs
# - Monitoreo
# - Eureka
# - Config Server
# - Microservicios
spring.application.name=products-api


# =========================================================
# PUERTO DEL SERVIDOR
# =========================================================

# Puerto donde arrancara la aplicacion.
#
# La API estara disponible en:
#
# http://localhost:8080
server.port=8080


# =========================================================
# CONFIGURACION DEL CANAL DE SALIDA
# =========================================================

# commands-out-0
#
# commands     -> nombre del canal
# out          -> indica que los mensajes SALEN de la aplicacion
# 0            -> indice del canal
#
# El indice permite tener multiples canales:
#
# commands-out-0
# commands-out-1
# commands-out-2
#
# Cada canal podria enviar mensajes a diferentes topics.
#
# destination define el topic Kafka destino.
#
# Todo mensaje enviado por este canal sera publicado
# en el topic:
#
# products.commands
spring.cloud.stream.bindings.commands-out-0.destination=products.commands


# Define el tipo de contenido que sera enviado.
#
# application/json significa:
#
# Los objetos Java se convertiran automaticamente
# a formato JSON antes de enviarse a Kafka.
#
# Ejemplo:
#
# ProductDto -> JSON
spring.cloud.stream.bindings.commands-out-0.content-type=application/json


# =========================================================
# CONFIGURACION DEL BROKER KAFKA
# =========================================================

# Define la direccion del servidor Kafka.
# Un broker es un servidor que forma parte del cluster de Kafka y
# se encarga de almacenar y distribuir los mensajes.
#
# localhost -> Kafka corre localmente
# 9092      -> puerto por defecto de Kafka
# kafka      -> nombre del contenedor Docker donde esta Kafka
# La aplicacion se conectara a Kafka usando:
# 19092      -> puerto expuesto por el contenedor Docker
#
# localhost:9092
## spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.kafka.binder.brokers=kafka:19092

# =========================================================
# CONFIGURACION DEL CANAL DE ENTRADA
# =========================================================
# Define la funcion que procesara los mensajes entrantes.
# En este caso, la funcion se llama "handleReplies()".
# Spring buscara automaticamente el metodo Bean:
# @Bean public Function<ReplyDto, Void> handleReplies() { ... }
# y lo conectara al canal de entrada.
spring.cloud.function.definition=handleReplies
# Define el topic Kafka del cual se leeran los mensajes.
# products.replies -> topic donde se publican las respuestas
# La aplicacion se suscribira a este topic para recibir mensajes.
spring.cloud.stream.bindings.handleReplies-in-0.destination=products.replies
# Define el tipo de contenido que se espera recibir.
spring.cloud.stream.bindings.handleReplies-in-0.content-type=application/json
# Define el grupo de consumidores para este canal.
spring.cloud.stream.bindings.handleReplies-in-0.group=products-api
# Define el offset de inicio para los consumidores.
# latest -> solo se procesaran los mensajes nuevos que lleguen al topic despues de que la aplicacion haya arrancado.
spring.cloud.stream.kafka.bindings.handleReplies-in-0.consumer.startOffset=latest
