spring.application.name=products-api
server.port=8080
# commands-out-0 canal de comunicacion out indica que sale de nuestra aplicacion, y el indice 0 indica un canal especifico
# por que podemos tener varios canales ejemplo commands-out-1
spring.cloud.stream.bindings.commands-out-0.destination=products.commands
spring.cloud.stream.bindings.commands-out-0.content-type=application/json

spring.cloud.stream.kafka.binder.brokers=localhost:9092