# =========================================================
# NOMBRE DE LA APLICACION
# =========================================================

# Define el nombre de la aplicacion dentro del ecosistema Spring.
#
# Este nombre puede ser utilizado en:
#
# - Logs
# - Monitoreo
# - Eureka
# - Config Server
# - Microservicios
spring.application.name=products-api


# =========================================================
# PUERTO DEL SERVIDOR
# =========================================================

# Puerto donde arrancara la aplicacion.
#
# La API estara disponible en:
#
# http://localhost:8080
server.port=8080


# =========================================================
# CONFIGURACION DEL CANAL DE SALIDA
# =========================================================

# commands-out-0
#
# commands     -> nombre del canal
# out          -> indica que los mensajes SALEN de la aplicacion
# 0            -> indice del canal
#
# El indice permite tener multiples canales:
#
# commands-out-0
# commands-out-1
# commands-out-2
#
# Cada canal podria enviar mensajes a diferentes topics.
#
# destination define el topic Kafka destino.
#
# Todo mensaje enviado por este canal sera publicado
# en el topic:
#
# products.commands
spring.cloud.stream.bindings.commands-out-0.destination=products.commands


# Define el tipo de contenido que sera enviado.
#
# application/json significa:
#
# Los objetos Java se convertiran automaticamente
# a formato JSON antes de enviarse a Kafka.
#
# Ejemplo:
#
# ProductDto -> JSON
spring.cloud.stream.bindings.commands-out-0.content-type=application/json


# =========================================================
# CONFIGURACION DEL BROKER KAFKA
# =========================================================

# Define la direccion del servidor Kafka.
#
# localhost -> Kafka corre localmente
# 9092      -> puerto por defecto de Kafka
#
# La aplicacion se conectara a Kafka usando:
#
# localhost:9092
spring.cloud.stream.kafka.binder.brokers=localhost:9092